//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravillioXMLOutService.AllocationEnquiryService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
    public partial class ResponseDataFaultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultDescriptionField;
        
        private string faultCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FaultDescription {
            get {
                return this.faultDescriptionField;
            }
            set {
                this.faultDescriptionField = value;
                this.RaisePropertyChanged("FaultDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FaultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("FaultCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
    public partial class InfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestBaseType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
    public partial class AgentBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string agentCodeField;
        
        private string agentPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AgentCode {
            get {
                return this.agentCodeField;
            }
            set {
                this.agentCodeField = value;
                this.RaisePropertyChanged("AgentCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AgentPassword {
            get {
                return this.agentPasswordField;
            }
            set {
                this.agentPasswordField = value;
                this.RaisePropertyChanged("AgentPassword");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
    public partial class RequestBaseType : AgentBaseType {
        
        private string langField;
        
        public RequestBaseType() {
            this.langField = "en-GB";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("en-GB")]
        public string Lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("Lang");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.travco.co.uk/trlink/xsd/allocationenquiryv7/response")]
    public partial class Allocation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InfoType informationField;
        
        private string statusField;
        
        private string hotelNameField;
        
        private string roomNameField;
        
        private string hotelStarField;
        
        private string hotelStarCodeField;
        
        private string adultPriceDetailField;
        
        private string childPriceDetailField;
        
        private string specialMessageField;
        
        private string priceMessageField;
        
        private string currencyNameField;
        
        private AllocationReducedPriceDetails reducedPriceDetailsField;
        
        private AllocationFreeNightsDetails freeNightsDetailsField;
        
        private AllocationHotelMessage[] hotelMessagesField;
        
        private AllocationRatePlanDetails ratePlanDetailsField;
        
        private string enquiryNoField;
        
        private string noOfAdultsField;
        
        private string noOfChildField;
        
        private string durationField;
        
        private System.DateTime dateField;
        
        private string hotelCodeField;
        
        private string roomCodeField;
        
        private System.DateTime lastAvailableDateField;
        
        private bool lastAvailableDateFieldSpecified;
        
        private System.DateTime nextAvailableDateField;
        
        private bool nextAvailableDateFieldSpecified;
        
        private float adultPriceField;
        
        private bool adultPriceFieldSpecified;
        
        private float childPriceField;
        
        private bool childPriceFieldSpecified;
        
        private float totalAdultPriceField;
        
        private bool totalAdultPriceFieldSpecified;
        
        private float totalChildPriceField;
        
        private bool totalChildPriceFieldSpecified;
        
        private string currencyCodeField;
        
        private string priceCodeField;
        
        private string specialIndicatorField;
        
        private string cancellationChargeCodeField;
        
        private string cancellationChargeOverlapCodeField;
        
        private string noOfPassengerInRoomField;
        
        private string noOfExtraBedField;
        
        private string extraBedIndicatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public InfoType Information {
            get {
                return this.informationField;
            }
            set {
                this.informationField = value;
                this.RaisePropertyChanged("Information");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string HotelName {
            get {
                return this.hotelNameField;
            }
            set {
                this.hotelNameField = value;
                this.RaisePropertyChanged("HotelName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string RoomName {
            get {
                return this.roomNameField;
            }
            set {
                this.roomNameField = value;
                this.RaisePropertyChanged("RoomName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string HotelStar {
            get {
                return this.hotelStarField;
            }
            set {
                this.hotelStarField = value;
                this.RaisePropertyChanged("HotelStar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string HotelStarCode {
            get {
                return this.hotelStarCodeField;
            }
            set {
                this.hotelStarCodeField = value;
                this.RaisePropertyChanged("HotelStarCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string AdultPriceDetail {
            get {
                return this.adultPriceDetailField;
            }
            set {
                this.adultPriceDetailField = value;
                this.RaisePropertyChanged("AdultPriceDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ChildPriceDetail {
            get {
                return this.childPriceDetailField;
            }
            set {
                this.childPriceDetailField = value;
                this.RaisePropertyChanged("ChildPriceDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SpecialMessage {
            get {
                return this.specialMessageField;
            }
            set {
                this.specialMessageField = value;
                this.RaisePropertyChanged("SpecialMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string PriceMessage {
            get {
                return this.priceMessageField;
            }
            set {
                this.priceMessageField = value;
                this.RaisePropertyChanged("PriceMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string CurrencyName {
            get {
                return this.currencyNameField;
            }
            set {
                this.currencyNameField = value;
                this.RaisePropertyChanged("CurrencyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public AllocationReducedPriceDetails ReducedPriceDetails {
            get {
                return this.reducedPriceDetailsField;
            }
            set {
                this.reducedPriceDetailsField = value;
                this.RaisePropertyChanged("ReducedPriceDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public AllocationFreeNightsDetails FreeNightsDetails {
            get {
                return this.freeNightsDetailsField;
            }
            set {
                this.freeNightsDetailsField = value;
                this.RaisePropertyChanged("FreeNightsDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        [System.Xml.Serialization.XmlArrayItemAttribute("HotelMessage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AllocationHotelMessage[] HotelMessages {
            get {
                return this.hotelMessagesField;
            }
            set {
                this.hotelMessagesField = value;
                this.RaisePropertyChanged("HotelMessages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public AllocationRatePlanDetails RatePlanDetails {
            get {
                return this.ratePlanDetailsField;
            }
            set {
                this.ratePlanDetailsField = value;
                this.RaisePropertyChanged("RatePlanDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string EnquiryNo {
            get {
                return this.enquiryNoField;
            }
            set {
                this.enquiryNoField = value;
                this.RaisePropertyChanged("EnquiryNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string NoOfAdults {
            get {
                return this.noOfAdultsField;
            }
            set {
                this.noOfAdultsField = value;
                this.RaisePropertyChanged("NoOfAdults");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string NoOfChild {
            get {
                return this.noOfChildField;
            }
            set {
                this.noOfChildField = value;
                this.RaisePropertyChanged("NoOfChild");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("Duration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HotelCode {
            get {
                return this.hotelCodeField;
            }
            set {
                this.hotelCodeField = value;
                this.RaisePropertyChanged("HotelCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RoomCode {
            get {
                return this.roomCodeField;
            }
            set {
                this.roomCodeField = value;
                this.RaisePropertyChanged("RoomCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime LastAvailableDate {
            get {
                return this.lastAvailableDateField;
            }
            set {
                this.lastAvailableDateField = value;
                this.RaisePropertyChanged("LastAvailableDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastAvailableDateSpecified {
            get {
                return this.lastAvailableDateFieldSpecified;
            }
            set {
                this.lastAvailableDateFieldSpecified = value;
                this.RaisePropertyChanged("LastAvailableDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime NextAvailableDate {
            get {
                return this.nextAvailableDateField;
            }
            set {
                this.nextAvailableDateField = value;
                this.RaisePropertyChanged("NextAvailableDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NextAvailableDateSpecified {
            get {
                return this.nextAvailableDateFieldSpecified;
            }
            set {
                this.nextAvailableDateFieldSpecified = value;
                this.RaisePropertyChanged("NextAvailableDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float AdultPrice {
            get {
                return this.adultPriceField;
            }
            set {
                this.adultPriceField = value;
                this.RaisePropertyChanged("AdultPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdultPriceSpecified {
            get {
                return this.adultPriceFieldSpecified;
            }
            set {
                this.adultPriceFieldSpecified = value;
                this.RaisePropertyChanged("AdultPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float ChildPrice {
            get {
                return this.childPriceField;
            }
            set {
                this.childPriceField = value;
                this.RaisePropertyChanged("ChildPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChildPriceSpecified {
            get {
                return this.childPriceFieldSpecified;
            }
            set {
                this.childPriceFieldSpecified = value;
                this.RaisePropertyChanged("ChildPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float TotalAdultPrice {
            get {
                return this.totalAdultPriceField;
            }
            set {
                this.totalAdultPriceField = value;
                this.RaisePropertyChanged("TotalAdultPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalAdultPriceSpecified {
            get {
                return this.totalAdultPriceFieldSpecified;
            }
            set {
                this.totalAdultPriceFieldSpecified = value;
                this.RaisePropertyChanged("TotalAdultPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float TotalChildPrice {
            get {
                return this.totalChildPriceField;
            }
            set {
                this.totalChildPriceField = value;
                this.RaisePropertyChanged("TotalChildPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalChildPriceSpecified {
            get {
                return this.totalChildPriceFieldSpecified;
            }
            set {
                this.totalChildPriceFieldSpecified = value;
                this.RaisePropertyChanged("TotalChildPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
                this.RaisePropertyChanged("CurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PriceCode {
            get {
                return this.priceCodeField;
            }
            set {
                this.priceCodeField = value;
                this.RaisePropertyChanged("PriceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SpecialIndicator {
            get {
                return this.specialIndicatorField;
            }
            set {
                this.specialIndicatorField = value;
                this.RaisePropertyChanged("SpecialIndicator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CancellationChargeCode {
            get {
                return this.cancellationChargeCodeField;
            }
            set {
                this.cancellationChargeCodeField = value;
                this.RaisePropertyChanged("CancellationChargeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CancellationChargeOverlapCode {
            get {
                return this.cancellationChargeOverlapCodeField;
            }
            set {
                this.cancellationChargeOverlapCodeField = value;
                this.RaisePropertyChanged("CancellationChargeOverlapCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string NoOfPassengerInRoom {
            get {
                return this.noOfPassengerInRoomField;
            }
            set {
                this.noOfPassengerInRoomField = value;
                this.RaisePropertyChanged("NoOfPassengerInRoom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string NoOfExtraBed {
            get {
                return this.noOfExtraBedField;
            }
            set {
                this.noOfExtraBedField = value;
                this.RaisePropertyChanged("NoOfExtraBed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExtraBedIndicator {
            get {
                return this.extraBedIndicatorField;
            }
            set {
                this.extraBedIndicatorField = value;
                this.RaisePropertyChanged("ExtraBedIndicator");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.travco.co.uk/trlink/xsd/allocationenquiryv7/response")]
    public partial class AllocationReducedPriceDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private float adultReductionAmountField;
        
        private bool adultReductionAmountFieldSpecified;
        
        private decimal adultReductionPercentageField;
        
        private bool adultReductionPercentageFieldSpecified;
        
        private float childReductionAmountField;
        
        private bool childReductionAmountFieldSpecified;
        
        private decimal childReductionPercentageField;
        
        private bool childReductionPercentageFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float AdultReductionAmount {
            get {
                return this.adultReductionAmountField;
            }
            set {
                this.adultReductionAmountField = value;
                this.RaisePropertyChanged("AdultReductionAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdultReductionAmountSpecified {
            get {
                return this.adultReductionAmountFieldSpecified;
            }
            set {
                this.adultReductionAmountFieldSpecified = value;
                this.RaisePropertyChanged("AdultReductionAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal AdultReductionPercentage {
            get {
                return this.adultReductionPercentageField;
            }
            set {
                this.adultReductionPercentageField = value;
                this.RaisePropertyChanged("AdultReductionPercentage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdultReductionPercentageSpecified {
            get {
                return this.adultReductionPercentageFieldSpecified;
            }
            set {
                this.adultReductionPercentageFieldSpecified = value;
                this.RaisePropertyChanged("AdultReductionPercentageSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float ChildReductionAmount {
            get {
                return this.childReductionAmountField;
            }
            set {
                this.childReductionAmountField = value;
                this.RaisePropertyChanged("ChildReductionAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChildReductionAmountSpecified {
            get {
                return this.childReductionAmountFieldSpecified;
            }
            set {
                this.childReductionAmountFieldSpecified = value;
                this.RaisePropertyChanged("ChildReductionAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ChildReductionPercentage {
            get {
                return this.childReductionPercentageField;
            }
            set {
                this.childReductionPercentageField = value;
                this.RaisePropertyChanged("ChildReductionPercentage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChildReductionPercentageSpecified {
            get {
                return this.childReductionPercentageFieldSpecified;
            }
            set {
                this.childReductionPercentageFieldSpecified = value;
                this.RaisePropertyChanged("ChildReductionPercentageSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.travco.co.uk/trlink/xsd/allocationenquiryv7/response")]
    public partial class AllocationFreeNightsDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string noOfAdultFreeNightsField;
        
        private float adultFreeNightsPriceField;
        
        private bool adultFreeNightsPriceFieldSpecified;
        
        private string minimumAdultDurationField;
        
        private string noOfChildFreeNightsField;
        
        private float childFreeNightsPriceField;
        
        private bool childFreeNightsPriceFieldSpecified;
        
        private string minimumChildDurationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string NoOfAdultFreeNights {
            get {
                return this.noOfAdultFreeNightsField;
            }
            set {
                this.noOfAdultFreeNightsField = value;
                this.RaisePropertyChanged("NoOfAdultFreeNights");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float AdultFreeNightsPrice {
            get {
                return this.adultFreeNightsPriceField;
            }
            set {
                this.adultFreeNightsPriceField = value;
                this.RaisePropertyChanged("AdultFreeNightsPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdultFreeNightsPriceSpecified {
            get {
                return this.adultFreeNightsPriceFieldSpecified;
            }
            set {
                this.adultFreeNightsPriceFieldSpecified = value;
                this.RaisePropertyChanged("AdultFreeNightsPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string MinimumAdultDuration {
            get {
                return this.minimumAdultDurationField;
            }
            set {
                this.minimumAdultDurationField = value;
                this.RaisePropertyChanged("MinimumAdultDuration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string NoOfChildFreeNights {
            get {
                return this.noOfChildFreeNightsField;
            }
            set {
                this.noOfChildFreeNightsField = value;
                this.RaisePropertyChanged("NoOfChildFreeNights");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float ChildFreeNightsPrice {
            get {
                return this.childFreeNightsPriceField;
            }
            set {
                this.childFreeNightsPriceField = value;
                this.RaisePropertyChanged("ChildFreeNightsPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChildFreeNightsPriceSpecified {
            get {
                return this.childFreeNightsPriceFieldSpecified;
            }
            set {
                this.childFreeNightsPriceFieldSpecified = value;
                this.RaisePropertyChanged("ChildFreeNightsPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string MinimumChildDuration {
            get {
                return this.minimumChildDurationField;
            }
            set {
                this.minimumChildDurationField = value;
                this.RaisePropertyChanged("MinimumChildDuration");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.travco.co.uk/trlink/xsd/allocationenquiryv7/response")]
    public partial class AllocationHotelMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hotelMessageTextField;
        
        private string hotelMessageCodeField;
        
        private System.DateTime fromDateField;
        
        private System.DateTime toDateField;
        
        private AllocationHotelMessageMessageIndicator messageIndicatorField;
        
        private bool messageIndicatorFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string HotelMessageText {
            get {
                return this.hotelMessageTextField;
            }
            set {
                this.hotelMessageTextField = value;
                this.RaisePropertyChanged("HotelMessageText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HotelMessageCode {
            get {
                return this.hotelMessageCodeField;
            }
            set {
                this.hotelMessageCodeField = value;
                this.RaisePropertyChanged("HotelMessageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime FromDate {
            get {
                return this.fromDateField;
            }
            set {
                this.fromDateField = value;
                this.RaisePropertyChanged("FromDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime ToDate {
            get {
                return this.toDateField;
            }
            set {
                this.toDateField = value;
                this.RaisePropertyChanged("ToDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AllocationHotelMessageMessageIndicator MessageIndicator {
            get {
                return this.messageIndicatorField;
            }
            set {
                this.messageIndicatorField = value;
                this.RaisePropertyChanged("MessageIndicator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MessageIndicatorSpecified {
            get {
                return this.messageIndicatorFieldSpecified;
            }
            set {
                this.messageIndicatorFieldSpecified = value;
                this.RaisePropertyChanged("MessageIndicatorSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.travco.co.uk/trlink/xsd/allocationenquiryv7/response")]
    public enum AllocationHotelMessageMessageIndicator {
        
        /// <remarks/>
        Block,
        
        /// <remarks/>
        Information,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.travco.co.uk/trlink/xsd/allocationenquiryv7/response")]
    public partial class AllocationRatePlanDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ratePlanDescriptionField;
        
        private string ratePlanCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string RatePlanDescription {
            get {
                return this.ratePlanDescriptionField;
            }
            set {
                this.ratePlanDescriptionField = value;
                this.RaisePropertyChanged("RatePlanDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RatePlanCode {
            get {
                return this.ratePlanCodeField;
            }
            set {
                this.ratePlanCodeField = value;
                this.RaisePropertyChanged("RatePlanCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
    public partial class ReceiveParserFaultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultDescriptionField;
        
        private string faultCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FaultDescription {
            get {
                return this.faultDescriptionField;
            }
            set {
                this.faultDescriptionField = value;
                this.RaisePropertyChanged("FaultDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FaultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("FaultCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
    public partial class SendParserFaultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultDescriptionField;
        
        private string faultCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FaultDescription {
            get {
                return this.faultDescriptionField;
            }
            set {
                this.faultDescriptionField = value;
                this.RaisePropertyChanged("FaultDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FaultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("FaultCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
    public partial class UserFaultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultDescriptionField;
        
        private string faultCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FaultDescription {
            get {
                return this.faultDescriptionField;
            }
            set {
                this.faultDescriptionField = value;
                this.RaisePropertyChanged("FaultDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FaultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("FaultCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
    public partial class CommunicationFaultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultDescriptionField;
        
        private string faultCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FaultDescription {
            get {
                return this.faultDescriptionField;
            }
            set {
                this.faultDescriptionField = value;
                this.RaisePropertyChanged("FaultDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FaultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("FaultCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
    public partial class ServerFaultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultDescriptionField;
        
        private string faultCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FaultDescription {
            get {
                return this.faultDescriptionField;
            }
            set {
                this.faultDescriptionField = value;
                this.RaisePropertyChanged("FaultDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FaultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("FaultCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.travco.co.uk/", ConfigurationName="AllocationEnquiryService.AllocationEnquiryV7ServicePortType")]
    public interface AllocationEnquiryV7ServicePortType {
        
        // CODEGEN: Generating message contract since the operation getAllocationEnquiry is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getAllocationEnquiry", ReplyAction="urn:getAllocationEnquiryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.AllocationEnquiryService.ResponseDataFaultType), Action="urn:getAllocationEnquiry", Name="ResponseDataFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.AllocationEnquiryService.ReceiveParserFaultType), Action="urn:getAllocationEnquiry", Name="ReceiveParserFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.AllocationEnquiryService.SendParserFaultType), Action="urn:getAllocationEnquiry", Name="SendParserFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.AllocationEnquiryService.UserFaultType), Action="urn:getAllocationEnquiry", Name="UserFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.AllocationEnquiryService.CommunicationFaultType), Action="urn:getAllocationEnquiry", Name="CommunicationFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.AllocationEnquiryService.ServerFaultType), Action="urn:getAllocationEnquiry", Name="ServerFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgentBaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Allocation[]))]
        TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryResponse getAllocationEnquiry(TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getAllocationEnquiry", ReplyAction="urn:getAllocationEnquiryResponse")]
        System.Threading.Tasks.Task<TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryResponse> getAllocationEnquiryAsync(TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryRequest request);
        
        // CODEGEN: Generating message contract since the operation getAllocationEnquiryForEnquiry is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getAllocationEnquiryForEnquiry", ReplyAction="urn:getAllocationEnquiryForEnquiryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.AllocationEnquiryService.ResponseDataFaultType), Action="urn:getAllocationEnquiryForEnquiry", Name="ResponseDataFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.AllocationEnquiryService.ReceiveParserFaultType), Action="urn:getAllocationEnquiryForEnquiry", Name="ReceiveParserFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.AllocationEnquiryService.SendParserFaultType), Action="urn:getAllocationEnquiryForEnquiry", Name="SendParserFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.AllocationEnquiryService.UserFaultType), Action="urn:getAllocationEnquiryForEnquiry", Name="UserFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.AllocationEnquiryService.CommunicationFaultType), Action="urn:getAllocationEnquiryForEnquiry", Name="CommunicationFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.AllocationEnquiryService.ServerFaultType), Action="urn:getAllocationEnquiryForEnquiry", Name="ServerFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgentBaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Allocation[]))]
        TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryResponse getAllocationEnquiryForEnquiry(TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getAllocationEnquiryForEnquiry", ReplyAction="urn:getAllocationEnquiryForEnquiryResponse")]
        System.Threading.Tasks.Task<TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryResponse> getAllocationEnquiryForEnquiryAsync(TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiryRequest request);
        
        // CODEGEN: Generating message contract since the operation getAllocationEnquiryForEnquiries is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getAllocationEnquiryForEnquiries", ReplyAction="urn:getAllocationEnquiryForEnquiriesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.AllocationEnquiryService.ResponseDataFaultType), Action="urn:getAllocationEnquiryForEnquiries", Name="ResponseDataFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.AllocationEnquiryService.ReceiveParserFaultType), Action="urn:getAllocationEnquiryForEnquiries", Name="ReceiveParserFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.AllocationEnquiryService.SendParserFaultType), Action="urn:getAllocationEnquiryForEnquiries", Name="SendParserFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.AllocationEnquiryService.UserFaultType), Action="urn:getAllocationEnquiryForEnquiries", Name="UserFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.AllocationEnquiryService.CommunicationFaultType), Action="urn:getAllocationEnquiryForEnquiries", Name="CommunicationFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.AllocationEnquiryService.ServerFaultType), Action="urn:getAllocationEnquiryForEnquiries", Name="ServerFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgentBaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Allocation[]))]
        TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryResponse getAllocationEnquiryForEnquiries(TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getAllocationEnquiryForEnquiries", ReplyAction="urn:getAllocationEnquiryForEnquiriesResponse")]
        System.Threading.Tasks.Task<TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryResponse> getAllocationEnquiryForEnquiriesAsync(TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiriesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.travco.co.uk/trlink/xsd/allocationenquiryv7/request")]
    public partial class getAllocationEnquiry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestBaseType requestBaseField;
        
        private string enquiryNoField;
        
        private string hotelCodeField;
        
        private string noOfAdultsField;
        
        private string noOfChildrenField;
        
        private string durationField;
        
        private System.DateTime checkInDateField;
        
        private string noOfPaxInRoomField;
        
        private AdditionalData additionalDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestBaseType RequestBase {
            get {
                return this.requestBaseField;
            }
            set {
                this.requestBaseField = value;
                this.RaisePropertyChanged("RequestBase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EnquiryNo {
            get {
                return this.enquiryNoField;
            }
            set {
                this.enquiryNoField = value;
                this.RaisePropertyChanged("EnquiryNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string HotelCode {
            get {
                return this.hotelCodeField;
            }
            set {
                this.hotelCodeField = value;
                this.RaisePropertyChanged("HotelCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=3)]
        public string NoOfAdults {
            get {
                return this.noOfAdultsField;
            }
            set {
                this.noOfAdultsField = value;
                this.RaisePropertyChanged("NoOfAdults");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=4)]
        public string NoOfChildren {
            get {
                return this.noOfChildrenField;
            }
            set {
                this.noOfChildrenField = value;
                this.RaisePropertyChanged("NoOfChildren");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=5)]
        public string Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("Duration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime CheckInDate {
            get {
                return this.checkInDateField;
            }
            set {
                this.checkInDateField = value;
                this.RaisePropertyChanged("CheckInDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=7)]
        public string NoOfPaxInRoom {
            get {
                return this.noOfPaxInRoomField;
            }
            set {
                this.noOfPaxInRoomField = value;
                this.RaisePropertyChanged("NoOfPaxInRoom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public AdditionalData AdditionalData {
            get {
                return this.additionalDataField;
            }
            set {
                this.additionalDataField = value;
                this.RaisePropertyChanged("AdditionalData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.travco.co.uk/trlink/xsd/allocationenquiryv7/request")]
    public partial class AdditionalData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private YesNoType needReductionAmountField;
        
        private YesNoType needHotelMessagesField;
        
        private YesNoType needFreeNightDetailsField;
        
        public AdditionalData() {
            this.needReductionAmountField = YesNoType.no;
            this.needHotelMessagesField = YesNoType.no;
            this.needFreeNightDetailsField = YesNoType.no;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(YesNoType.no)]
        public YesNoType NeedReductionAmount {
            get {
                return this.needReductionAmountField;
            }
            set {
                this.needReductionAmountField = value;
                this.RaisePropertyChanged("NeedReductionAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(YesNoType.no)]
        public YesNoType NeedHotelMessages {
            get {
                return this.needHotelMessagesField;
            }
            set {
                this.needHotelMessagesField = value;
                this.RaisePropertyChanged("NeedHotelMessages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(YesNoType.no)]
        public YesNoType NeedFreeNightDetails {
            get {
                return this.needFreeNightDetailsField;
            }
            set {
                this.needFreeNightDetailsField = value;
                this.RaisePropertyChanged("NeedFreeNightDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/simpletype")]
    public enum YesNoType {
        
        /// <remarks/>
        yes,
        
        /// <remarks/>
        no,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.travco.co.uk/trlink/xsd/allocationenquiryv7/response")]
    public partial class AllocationEnquiryV7Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Response responseField;
        
        private string langTypeField;
        
        public AllocationEnquiryV7Response() {
            this.langTypeField = "en-GB";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Response Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("en-GB")]
        public string LangType {
            get {
                return this.langTypeField;
            }
            set {
                this.langTypeField = value;
                this.RaisePropertyChanged("LangType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.travco.co.uk/trlink/xsd/allocationenquiryv7/response")]
    public partial class Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InfoType informationField;
        
        private Allocation[] allocationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public InfoType Information {
            get {
                return this.informationField;
            }
            set {
                this.informationField = value;
                this.RaisePropertyChanged("Information");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Allocation", IsNullable=false)]
        public Allocation[] Allocations {
            get {
                return this.allocationsField;
            }
            set {
                this.allocationsField = value;
                this.RaisePropertyChanged("Allocations");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllocationEnquiryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/allocationenquiryv7/request", Order=0)]
        public TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiry getAllocationEnquiry;
        
        public getAllocationEnquiryRequest() {
        }
        
        public getAllocationEnquiryRequest(TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiry getAllocationEnquiry) {
            this.getAllocationEnquiry = getAllocationEnquiry;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllocationEnquiryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/allocationenquiryv7/response", Order=0)]
        public TravillioXMLOutService.AllocationEnquiryService.AllocationEnquiryV7Response AllocationEnquiryV7Response;
        
        public getAllocationEnquiryResponse() {
        }
        
        public getAllocationEnquiryResponse(TravillioXMLOutService.AllocationEnquiryService.AllocationEnquiryV7Response AllocationEnquiryV7Response) {
            this.AllocationEnquiryV7Response = AllocationEnquiryV7Response;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.travco.co.uk/trlink/xsd/allocationenquiryv7/request")]
    public partial class getAllocationEnquiryForEnquiry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestBaseType requestBaseField;
        
        private Enquiry enquiryField;
        
        private AdditionalData additionalDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestBaseType RequestBase {
            get {
                return this.requestBaseField;
            }
            set {
                this.requestBaseField = value;
                this.RaisePropertyChanged("RequestBase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Enquiry Enquiry {
            get {
                return this.enquiryField;
            }
            set {
                this.enquiryField = value;
                this.RaisePropertyChanged("Enquiry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public AdditionalData AdditionalData {
            get {
                return this.additionalDataField;
            }
            set {
                this.additionalDataField = value;
                this.RaisePropertyChanged("AdditionalData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.travco.co.uk/trlink/xsd/allocationenquiryv7/request")]
    public partial class Enquiry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string enquiryNoField;
        
        private string hotelCodeField;
        
        private string noOfAdultsField;
        
        private string noOfChildrenField;
        
        private string durationField;
        
        private System.DateTime checkInDateField;
        
        private string noOfPaxInRoomField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EnquiryNo {
            get {
                return this.enquiryNoField;
            }
            set {
                this.enquiryNoField = value;
                this.RaisePropertyChanged("EnquiryNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HotelCode {
            get {
                return this.hotelCodeField;
            }
            set {
                this.hotelCodeField = value;
                this.RaisePropertyChanged("HotelCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=2)]
        public string NoOfAdults {
            get {
                return this.noOfAdultsField;
            }
            set {
                this.noOfAdultsField = value;
                this.RaisePropertyChanged("NoOfAdults");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=3)]
        public string NoOfChildren {
            get {
                return this.noOfChildrenField;
            }
            set {
                this.noOfChildrenField = value;
                this.RaisePropertyChanged("NoOfChildren");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=4)]
        public string Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("Duration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime CheckInDate {
            get {
                return this.checkInDateField;
            }
            set {
                this.checkInDateField = value;
                this.RaisePropertyChanged("CheckInDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=6)]
        public string NoOfPaxInRoom {
            get {
                return this.noOfPaxInRoomField;
            }
            set {
                this.noOfPaxInRoomField = value;
                this.RaisePropertyChanged("NoOfPaxInRoom");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllocationEnquiryForEnquiryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/allocationenquiryv7/request", Order=0)]
        public TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiry getAllocationEnquiryForEnquiry;
        
        public getAllocationEnquiryForEnquiryRequest() {
        }
        
        public getAllocationEnquiryForEnquiryRequest(TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiry getAllocationEnquiryForEnquiry) {
            this.getAllocationEnquiryForEnquiry = getAllocationEnquiryForEnquiry;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.travco.co.uk/trlink/xsd/allocationenquiryv7/request")]
    public partial class getAllocationEnquiryForEnquiries : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestBaseType requestBaseField;
        
        private Enquiry[] enquiriesField;
        
        private AdditionalData additionalDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestBaseType RequestBase {
            get {
                return this.requestBaseField;
            }
            set {
                this.requestBaseField = value;
                this.RaisePropertyChanged("RequestBase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Enquiry", IsNullable=false)]
        public Enquiry[] Enquiries {
            get {
                return this.enquiriesField;
            }
            set {
                this.enquiriesField = value;
                this.RaisePropertyChanged("Enquiries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public AdditionalData AdditionalData {
            get {
                return this.additionalDataField;
            }
            set {
                this.additionalDataField = value;
                this.RaisePropertyChanged("AdditionalData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllocationEnquiryForEnquiriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/allocationenquiryv7/request", Order=0)]
        public TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiries getAllocationEnquiryForEnquiries;
        
        public getAllocationEnquiryForEnquiriesRequest() {
        }
        
        public getAllocationEnquiryForEnquiriesRequest(TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiries getAllocationEnquiryForEnquiries) {
            this.getAllocationEnquiryForEnquiries = getAllocationEnquiryForEnquiries;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AllocationEnquiryV7ServicePortTypeChannel : TravillioXMLOutService.AllocationEnquiryService.AllocationEnquiryV7ServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AllocationEnquiryV7ServicePortTypeClient : System.ServiceModel.ClientBase<TravillioXMLOutService.AllocationEnquiryService.AllocationEnquiryV7ServicePortType>, TravillioXMLOutService.AllocationEnquiryService.AllocationEnquiryV7ServicePortType {
        
        public AllocationEnquiryV7ServicePortTypeClient() {
        }
        
        public AllocationEnquiryV7ServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AllocationEnquiryV7ServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllocationEnquiryV7ServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllocationEnquiryV7ServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryResponse TravillioXMLOutService.AllocationEnquiryService.AllocationEnquiryV7ServicePortType.getAllocationEnquiry(TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryRequest request) {
            return base.Channel.getAllocationEnquiry(request);
        }
        
        public TravillioXMLOutService.AllocationEnquiryService.AllocationEnquiryV7Response getAllocationEnquiry(TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiry getAllocationEnquiry1) {
            TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryRequest inValue = new TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryRequest();
            inValue.getAllocationEnquiry = getAllocationEnquiry1;
            TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryResponse retVal = ((TravillioXMLOutService.AllocationEnquiryService.AllocationEnquiryV7ServicePortType)(this)).getAllocationEnquiry(inValue);
            return retVal.AllocationEnquiryV7Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryResponse> TravillioXMLOutService.AllocationEnquiryService.AllocationEnquiryV7ServicePortType.getAllocationEnquiryAsync(TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryRequest request) {
            return base.Channel.getAllocationEnquiryAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryResponse> getAllocationEnquiryAsync(TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiry getAllocationEnquiry) {
            TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryRequest inValue = new TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryRequest();
            inValue.getAllocationEnquiry = getAllocationEnquiry;
            return ((TravillioXMLOutService.AllocationEnquiryService.AllocationEnquiryV7ServicePortType)(this)).getAllocationEnquiryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryResponse TravillioXMLOutService.AllocationEnquiryService.AllocationEnquiryV7ServicePortType.getAllocationEnquiryForEnquiry(TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiryRequest request) {
            return base.Channel.getAllocationEnquiryForEnquiry(request);
        }
        
        public TravillioXMLOutService.AllocationEnquiryService.AllocationEnquiryV7Response getAllocationEnquiryForEnquiry(TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiry getAllocationEnquiryForEnquiry1) {
            TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiryRequest inValue = new TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiryRequest();
            inValue.getAllocationEnquiryForEnquiry = getAllocationEnquiryForEnquiry1;
            TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryResponse retVal = ((TravillioXMLOutService.AllocationEnquiryService.AllocationEnquiryV7ServicePortType)(this)).getAllocationEnquiryForEnquiry(inValue);
            return retVal.AllocationEnquiryV7Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryResponse> TravillioXMLOutService.AllocationEnquiryService.AllocationEnquiryV7ServicePortType.getAllocationEnquiryForEnquiryAsync(TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiryRequest request) {
            return base.Channel.getAllocationEnquiryForEnquiryAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryResponse> getAllocationEnquiryForEnquiryAsync(TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiry getAllocationEnquiryForEnquiry) {
            TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiryRequest inValue = new TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiryRequest();
            inValue.getAllocationEnquiryForEnquiry = getAllocationEnquiryForEnquiry;
            return ((TravillioXMLOutService.AllocationEnquiryService.AllocationEnquiryV7ServicePortType)(this)).getAllocationEnquiryForEnquiryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryResponse TravillioXMLOutService.AllocationEnquiryService.AllocationEnquiryV7ServicePortType.getAllocationEnquiryForEnquiries(TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiriesRequest request) {
            return base.Channel.getAllocationEnquiryForEnquiries(request);
        }
        
        public TravillioXMLOutService.AllocationEnquiryService.AllocationEnquiryV7Response getAllocationEnquiryForEnquiries(TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiries getAllocationEnquiryForEnquiries1) {
            TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiriesRequest inValue = new TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiriesRequest();
            inValue.getAllocationEnquiryForEnquiries = getAllocationEnquiryForEnquiries1;
            TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryResponse retVal = ((TravillioXMLOutService.AllocationEnquiryService.AllocationEnquiryV7ServicePortType)(this)).getAllocationEnquiryForEnquiries(inValue);
            return retVal.AllocationEnquiryV7Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryResponse> TravillioXMLOutService.AllocationEnquiryService.AllocationEnquiryV7ServicePortType.getAllocationEnquiryForEnquiriesAsync(TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiriesRequest request) {
            return base.Channel.getAllocationEnquiryForEnquiriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryResponse> getAllocationEnquiryForEnquiriesAsync(TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiries getAllocationEnquiryForEnquiries) {
            TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiriesRequest inValue = new TravillioXMLOutService.AllocationEnquiryService.getAllocationEnquiryForEnquiriesRequest();
            inValue.getAllocationEnquiryForEnquiries = getAllocationEnquiryForEnquiries;
            return ((TravillioXMLOutService.AllocationEnquiryService.AllocationEnquiryV7ServicePortType)(this)).getAllocationEnquiryForEnquiriesAsync(inValue);
        }
    }
}
