//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravillioXMLOutService.HotelExtranet {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomSelfSearch", Namespace="http://schemas.datacontract.org/2004/07/ExtranetXMLOut.Entity")]
    [System.SerializableAttribute()]
    public partial class RoomSelfSearch : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AdulCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FillField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] child_agesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int rnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool verifyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AdulCount {
            get {
                return this.AdulCountField;
            }
            set {
                if ((this.AdulCountField.Equals(value) != true)) {
                    this.AdulCountField = value;
                    this.RaisePropertyChanged("AdulCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Fill {
            get {
                return this.FillField;
            }
            set {
                if ((this.FillField.Equals(value) != true)) {
                    this.FillField = value;
                    this.RaisePropertyChanged("Fill");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] child_ages {
            get {
                return this.child_agesField;
            }
            set {
                if ((object.ReferenceEquals(this.child_agesField, value) != true)) {
                    this.child_agesField = value;
                    this.RaisePropertyChanged("child_ages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rno {
            get {
                return this.rnoField;
            }
            set {
                if ((this.rnoField.Equals(value) != true)) {
                    this.rnoField = value;
                    this.RaisePropertyChanged("rno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool verify {
            get {
                return this.verifyField;
            }
            set {
                if ((this.verifyField.Equals(value) != true)) {
                    this.verifyField = value;
                    this.RaisePropertyChanged("verify");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HotelExtranet.IExtXmlOutService")]
    public interface IExtXmlOutService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/GetPropertyIdsByCityAndMainAgent", ReplyAction="http://tempuri.org/IExtXmlOutService/GetPropertyIdsByCityAndMainAgentResponse")]
        string GetPropertyIdsByCityAndMainAgent(string City, long MainAgent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/GetPropertyIdsByCityAndMainAgent", ReplyAction="http://tempuri.org/IExtXmlOutService/GetPropertyIdsByCityAndMainAgentResponse")]
        System.Threading.Tasks.Task<string> GetPropertyIdsByCityAndMainAgentAsync(string City, long MainAgent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/HotelDetailResponse", ReplyAction="http://tempuri.org/IExtXmlOutService/HotelDetailResponseResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TravillioXMLOutService.HotelExtranet.RoomSelfSearch[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TravillioXMLOutService.HotelExtranet.RoomSelfSearch))]
        object HotelDetailResponse(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/HotelDetailResponse", ReplyAction="http://tempuri.org/IExtXmlOutService/HotelDetailResponseResponse")]
        System.Threading.Tasks.Task<object> HotelDetailResponseAsync(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/CheckOnRequestStatusByXML", ReplyAction="http://tempuri.org/IExtXmlOutService/CheckOnRequestStatusByXMLResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TravillioXMLOutService.HotelExtranet.RoomSelfSearch[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TravillioXMLOutService.HotelExtranet.RoomSelfSearch))]
        object CheckOnRequestStatusByXML(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/CheckOnRequestStatusByXML", ReplyAction="http://tempuri.org/IExtXmlOutService/CheckOnRequestStatusByXMLResponse")]
        System.Threading.Tasks.Task<object> CheckOnRequestStatusByXMLAsync(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/MakeCancelBookingRequestByXML", ReplyAction="http://tempuri.org/IExtXmlOutService/MakeCancelBookingRequestByXMLResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TravillioXMLOutService.HotelExtranet.RoomSelfSearch[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TravillioXMLOutService.HotelExtranet.RoomSelfSearch))]
        object MakeCancelBookingRequestByXML(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/MakeCancelBookingRequestByXML", ReplyAction="http://tempuri.org/IExtXmlOutService/MakeCancelBookingRequestByXMLResponse")]
        System.Threading.Tasks.Task<object> MakeCancelBookingRequestByXMLAsync(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/MakeBookRequestByXML", ReplyAction="http://tempuri.org/IExtXmlOutService/MakeBookRequestByXMLResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TravillioXMLOutService.HotelExtranet.RoomSelfSearch[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TravillioXMLOutService.HotelExtranet.RoomSelfSearch))]
        object MakeBookRequestByXML(string request, int authentication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/MakeBookRequestByXML", ReplyAction="http://tempuri.org/IExtXmlOutService/MakeBookRequestByXMLResponse")]
        System.Threading.Tasks.Task<object> MakeBookRequestByXMLAsync(string request, int authentication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/GetData", ReplyAction="http://tempuri.org/IExtXmlOutService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/GetData", ReplyAction="http://tempuri.org/IExtXmlOutService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/GetQueryFromEntity", ReplyAction="http://tempuri.org/IExtXmlOutService/GetQueryFromEntityResponse")]
        string GetQueryFromEntity(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/GetQueryFromEntity", ReplyAction="http://tempuri.org/IExtXmlOutService/GetQueryFromEntityResponse")]
        System.Threading.Tasks.Task<string> GetQueryFromEntityAsync(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/GetSearchCityRequestByXML", ReplyAction="http://tempuri.org/IExtXmlOutService/GetSearchCityRequestByXMLResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TravillioXMLOutService.HotelExtranet.RoomSelfSearch[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TravillioXMLOutService.HotelExtranet.RoomSelfSearch))]
        object GetSearchCityRequestByXML(string request, bool For_Self);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/GetSearchCityRequestByXML", ReplyAction="http://tempuri.org/IExtXmlOutService/GetSearchCityRequestByXMLResponse")]
        System.Threading.Tasks.Task<object> GetSearchCityRequestByXMLAsync(string request, bool For_Self);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/GetPreBookRequestByXML", ReplyAction="http://tempuri.org/IExtXmlOutService/GetPreBookRequestByXMLResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TravillioXMLOutService.HotelExtranet.RoomSelfSearch[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TravillioXMLOutService.HotelExtranet.RoomSelfSearch))]
        object GetPreBookRequestByXML(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/GetPreBookRequestByXML", ReplyAction="http://tempuri.org/IExtXmlOutService/GetPreBookRequestByXMLResponse")]
        System.Threading.Tasks.Task<object> GetPreBookRequestByXMLAsync(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/GetCancelPolicyByXML", ReplyAction="http://tempuri.org/IExtXmlOutService/GetCancelPolicyByXMLResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TravillioXMLOutService.HotelExtranet.RoomSelfSearch[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TravillioXMLOutService.HotelExtranet.RoomSelfSearch))]
        object GetCancelPolicyByXML(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/GetCancelPolicyByXML", ReplyAction="http://tempuri.org/IExtXmlOutService/GetCancelPolicyByXMLResponse")]
        System.Threading.Tasks.Task<object> GetCancelPolicyByXMLAsync(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/GetSearchCityRequestByParameters", ReplyAction="http://tempuri.org/IExtXmlOutService/GetSearchCityRequestByParametersResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TravillioXMLOutService.HotelExtranet.RoomSelfSearch[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TravillioXMLOutService.HotelExtranet.RoomSelfSearch))]
        object GetSearchCityRequestByParameters(long contractId, long countryId, long cultureId, string City, System.DateTime C1, System.DateTime C2, TravillioXMLOutService.HotelExtranet.RoomSelfSearch[] room, long[] mid, string[] Stars, string hname, long[] ptid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/GetSearchCityRequestByParameters", ReplyAction="http://tempuri.org/IExtXmlOutService/GetSearchCityRequestByParametersResponse")]
        System.Threading.Tasks.Task<object> GetSearchCityRequestByParametersAsync(long contractId, long countryId, long cultureId, string City, System.DateTime C1, System.DateTime C2, TravillioXMLOutService.HotelExtranet.RoomSelfSearch[] room, long[] mid, string[] Stars, string hname, long[] ptid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/GetPreBookRequestByParameters", ReplyAction="http://tempuri.org/IExtXmlOutService/GetPreBookRequestByParametersResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TravillioXMLOutService.HotelExtranet.RoomSelfSearch[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TravillioXMLOutService.HotelExtranet.RoomSelfSearch))]
        object GetPreBookRequestByParameters(long PId, long RId, long MeId, string CountryId, long cultureId, System.DateTime C1, System.DateTime C2, TravillioXMLOutService.HotelExtranet.RoomSelfSearch[] room);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/GetPreBookRequestByParameters", ReplyAction="http://tempuri.org/IExtXmlOutService/GetPreBookRequestByParametersResponse")]
        System.Threading.Tasks.Task<object> GetPreBookRequestByParametersAsync(long PId, long RId, long MeId, string CountryId, long cultureId, System.DateTime C1, System.DateTime C2, TravillioXMLOutService.HotelExtranet.RoomSelfSearch[] room);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/CheckOnlyAvailabilityInCity", ReplyAction="http://tempuri.org/IExtXmlOutService/CheckOnlyAvailabilityInCityResponse")]
        bool CheckOnlyAvailabilityInCity(long contractId, long countryId, long cultureId, string City, System.DateTime C1, System.DateTime C2, TravillioXMLOutService.HotelExtranet.RoomSelfSearch[] room, long[] mid, string[] Stars, string hname, long[] ptid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/CheckOnlyAvailabilityInCity", ReplyAction="http://tempuri.org/IExtXmlOutService/CheckOnlyAvailabilityInCityResponse")]
        System.Threading.Tasks.Task<bool> CheckOnlyAvailabilityInCityAsync(long contractId, long countryId, long cultureId, string City, System.DateTime C1, System.DateTime C2, TravillioXMLOutService.HotelExtranet.RoomSelfSearch[] room, long[] mid, string[] Stars, string hname, long[] ptid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/GetSearchCityRequestByXML_New", ReplyAction="http://tempuri.org/IExtXmlOutService/GetSearchCityRequestByXML_NewResponse")]
        string GetSearchCityRequestByXML_New(long MainAgent, string contractId, long paxcountrycode, long cultureId, string citycode, System.DateTime C1, System.DateTime C2, TravillioXMLOutService.HotelExtranet.RoomSelfSearch[] room, long[] mid, string[] Stars, string hotelname, long[] ptid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtXmlOutService/GetSearchCityRequestByXML_New", ReplyAction="http://tempuri.org/IExtXmlOutService/GetSearchCityRequestByXML_NewResponse")]
        System.Threading.Tasks.Task<string> GetSearchCityRequestByXML_NewAsync(long MainAgent, string contractId, long paxcountrycode, long cultureId, string citycode, System.DateTime C1, System.DateTime C2, TravillioXMLOutService.HotelExtranet.RoomSelfSearch[] room, long[] mid, string[] Stars, string hotelname, long[] ptid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExtXmlOutServiceChannel : TravillioXMLOutService.HotelExtranet.IExtXmlOutService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExtXmlOutServiceClient : System.ServiceModel.ClientBase<TravillioXMLOutService.HotelExtranet.IExtXmlOutService>, TravillioXMLOutService.HotelExtranet.IExtXmlOutService {
        
        public ExtXmlOutServiceClient() {
        }
        
        public ExtXmlOutServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExtXmlOutServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExtXmlOutServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExtXmlOutServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetPropertyIdsByCityAndMainAgent(string City, long MainAgent) {
            return base.Channel.GetPropertyIdsByCityAndMainAgent(City, MainAgent);
        }
        
        public System.Threading.Tasks.Task<string> GetPropertyIdsByCityAndMainAgentAsync(string City, long MainAgent) {
            return base.Channel.GetPropertyIdsByCityAndMainAgentAsync(City, MainAgent);
        }
        
        public object HotelDetailResponse(string request) {
            return base.Channel.HotelDetailResponse(request);
        }
        
        public System.Threading.Tasks.Task<object> HotelDetailResponseAsync(string request) {
            return base.Channel.HotelDetailResponseAsync(request);
        }
        
        public object CheckOnRequestStatusByXML(string request) {
            return base.Channel.CheckOnRequestStatusByXML(request);
        }
        
        public System.Threading.Tasks.Task<object> CheckOnRequestStatusByXMLAsync(string request) {
            return base.Channel.CheckOnRequestStatusByXMLAsync(request);
        }
        
        public object MakeCancelBookingRequestByXML(string request) {
            return base.Channel.MakeCancelBookingRequestByXML(request);
        }
        
        public System.Threading.Tasks.Task<object> MakeCancelBookingRequestByXMLAsync(string request) {
            return base.Channel.MakeCancelBookingRequestByXMLAsync(request);
        }
        
        public object MakeBookRequestByXML(string request, int authentication) {
            return base.Channel.MakeBookRequestByXML(request, authentication);
        }
        
        public System.Threading.Tasks.Task<object> MakeBookRequestByXMLAsync(string request, int authentication) {
            return base.Channel.MakeBookRequestByXMLAsync(request, authentication);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string GetQueryFromEntity(string request) {
            return base.Channel.GetQueryFromEntity(request);
        }
        
        public System.Threading.Tasks.Task<string> GetQueryFromEntityAsync(string request) {
            return base.Channel.GetQueryFromEntityAsync(request);
        }
        
        public object GetSearchCityRequestByXML(string request, bool For_Self) {
            return base.Channel.GetSearchCityRequestByXML(request, For_Self);
        }
        
        public System.Threading.Tasks.Task<object> GetSearchCityRequestByXMLAsync(string request, bool For_Self) {
            return base.Channel.GetSearchCityRequestByXMLAsync(request, For_Self);
        }
        
        public object GetPreBookRequestByXML(string request) {
            return base.Channel.GetPreBookRequestByXML(request);
        }
        
        public System.Threading.Tasks.Task<object> GetPreBookRequestByXMLAsync(string request) {
            return base.Channel.GetPreBookRequestByXMLAsync(request);
        }
        
        public object GetCancelPolicyByXML(string request) {
            return base.Channel.GetCancelPolicyByXML(request);
        }
        
        public System.Threading.Tasks.Task<object> GetCancelPolicyByXMLAsync(string request) {
            return base.Channel.GetCancelPolicyByXMLAsync(request);
        }
        
        public object GetSearchCityRequestByParameters(long contractId, long countryId, long cultureId, string City, System.DateTime C1, System.DateTime C2, TravillioXMLOutService.HotelExtranet.RoomSelfSearch[] room, long[] mid, string[] Stars, string hname, long[] ptid) {
            return base.Channel.GetSearchCityRequestByParameters(contractId, countryId, cultureId, City, C1, C2, room, mid, Stars, hname, ptid);
        }
        
        public System.Threading.Tasks.Task<object> GetSearchCityRequestByParametersAsync(long contractId, long countryId, long cultureId, string City, System.DateTime C1, System.DateTime C2, TravillioXMLOutService.HotelExtranet.RoomSelfSearch[] room, long[] mid, string[] Stars, string hname, long[] ptid) {
            return base.Channel.GetSearchCityRequestByParametersAsync(contractId, countryId, cultureId, City, C1, C2, room, mid, Stars, hname, ptid);
        }
        
        public object GetPreBookRequestByParameters(long PId, long RId, long MeId, string CountryId, long cultureId, System.DateTime C1, System.DateTime C2, TravillioXMLOutService.HotelExtranet.RoomSelfSearch[] room) {
            return base.Channel.GetPreBookRequestByParameters(PId, RId, MeId, CountryId, cultureId, C1, C2, room);
        }
        
        public System.Threading.Tasks.Task<object> GetPreBookRequestByParametersAsync(long PId, long RId, long MeId, string CountryId, long cultureId, System.DateTime C1, System.DateTime C2, TravillioXMLOutService.HotelExtranet.RoomSelfSearch[] room) {
            return base.Channel.GetPreBookRequestByParametersAsync(PId, RId, MeId, CountryId, cultureId, C1, C2, room);
        }
        
        public bool CheckOnlyAvailabilityInCity(long contractId, long countryId, long cultureId, string City, System.DateTime C1, System.DateTime C2, TravillioXMLOutService.HotelExtranet.RoomSelfSearch[] room, long[] mid, string[] Stars, string hname, long[] ptid) {
            return base.Channel.CheckOnlyAvailabilityInCity(contractId, countryId, cultureId, City, C1, C2, room, mid, Stars, hname, ptid);
        }
        
        public System.Threading.Tasks.Task<bool> CheckOnlyAvailabilityInCityAsync(long contractId, long countryId, long cultureId, string City, System.DateTime C1, System.DateTime C2, TravillioXMLOutService.HotelExtranet.RoomSelfSearch[] room, long[] mid, string[] Stars, string hname, long[] ptid) {
            return base.Channel.CheckOnlyAvailabilityInCityAsync(contractId, countryId, cultureId, City, C1, C2, room, mid, Stars, hname, ptid);
        }
        
        public string GetSearchCityRequestByXML_New(long MainAgent, string contractId, long paxcountrycode, long cultureId, string citycode, System.DateTime C1, System.DateTime C2, TravillioXMLOutService.HotelExtranet.RoomSelfSearch[] room, long[] mid, string[] Stars, string hotelname, long[] ptid) {
            return base.Channel.GetSearchCityRequestByXML_New(MainAgent, contractId, paxcountrycode, cultureId, citycode, C1, C2, room, mid, Stars, hotelname, ptid);
        }
        
        public System.Threading.Tasks.Task<string> GetSearchCityRequestByXML_NewAsync(long MainAgent, string contractId, long paxcountrycode, long cultureId, string citycode, System.DateTime C1, System.DateTime C2, TravillioXMLOutService.HotelExtranet.RoomSelfSearch[] room, long[] mid, string[] Stars, string hotelname, long[] ptid) {
            return base.Channel.GetSearchCityRequestByXML_NewAsync(MainAgent, contractId, paxcountrycode, cultureId, citycode, C1, C2, room, mid, Stars, hotelname, ptid);
        }
    }
}
