//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravillioXMLOutService.HotelCancellationDetails {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
    public partial class ResponseDataFaultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultDescriptionField;
        
        private string faultCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FaultDescription {
            get {
                return this.faultDescriptionField;
            }
            set {
                this.faultDescriptionField = value;
                this.RaisePropertyChanged("FaultDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FaultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("FaultCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
    public partial class InfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestBaseType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
    public partial class AgentBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string agentCodeField;
        
        private string agentPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AgentCode {
            get {
                return this.agentCodeField;
            }
            set {
                this.agentCodeField = value;
                this.RaisePropertyChanged("AgentCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AgentPassword {
            get {
                return this.agentPasswordField;
            }
            set {
                this.agentPasswordField = value;
                this.RaisePropertyChanged("AgentPassword");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
    public partial class RequestBaseType : AgentBaseType {
        
        private string langField;
        
        public RequestBaseType() {
            this.langField = "en-GB";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("en-GB")]
        public string Lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("Lang");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.travco.co.uk/trlink/xsd/hotelcancellationdetail/response")]
    public partial class Detail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] fullCancellationPolicyField;
        
        private Message messageField;
        
        private System.DateTime effectiveFromField;
        
        private bool effectiveFromFieldSpecified;
        
        private string noOfDaysBeforeArrivalField;
        
        private string timeAfterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FullCancellationPolicy", Order=0)]
        public string[] FullCancellationPolicy {
            get {
                return this.fullCancellationPolicyField;
            }
            set {
                this.fullCancellationPolicyField = value;
                this.RaisePropertyChanged("FullCancellationPolicy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Message Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime EffectiveFrom {
            get {
                return this.effectiveFromField;
            }
            set {
                this.effectiveFromField = value;
                this.RaisePropertyChanged("EffectiveFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EffectiveFromSpecified {
            get {
                return this.effectiveFromFieldSpecified;
            }
            set {
                this.effectiveFromFieldSpecified = value;
                this.RaisePropertyChanged("EffectiveFromSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string NoOfDaysBeforeArrival {
            get {
                return this.noOfDaysBeforeArrivalField;
            }
            set {
                this.noOfDaysBeforeArrivalField = value;
                this.RaisePropertyChanged("NoOfDaysBeforeArrival");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TimeAfter {
            get {
                return this.timeAfterField;
            }
            set {
                this.timeAfterField = value;
                this.RaisePropertyChanged("TimeAfter");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.travco.co.uk/trlink/xsd/hotelcancellationdetail/response")]
    public partial class Message : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lastDateByWhichToCancelField;
        
        private string timeBeforeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastDateByWhichToCancel {
            get {
                return this.lastDateByWhichToCancelField;
            }
            set {
                this.lastDateByWhichToCancelField = value;
                this.RaisePropertyChanged("LastDateByWhichToCancel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TimeBefore {
            get {
                return this.timeBeforeField;
            }
            set {
                this.timeBeforeField = value;
                this.RaisePropertyChanged("TimeBefore");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
    public partial class ReceiveParserFaultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultDescriptionField;
        
        private string faultCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FaultDescription {
            get {
                return this.faultDescriptionField;
            }
            set {
                this.faultDescriptionField = value;
                this.RaisePropertyChanged("FaultDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FaultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("FaultCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
    public partial class SendParserFaultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultDescriptionField;
        
        private string faultCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FaultDescription {
            get {
                return this.faultDescriptionField;
            }
            set {
                this.faultDescriptionField = value;
                this.RaisePropertyChanged("FaultDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FaultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("FaultCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
    public partial class UserFaultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultDescriptionField;
        
        private string faultCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FaultDescription {
            get {
                return this.faultDescriptionField;
            }
            set {
                this.faultDescriptionField = value;
                this.RaisePropertyChanged("FaultDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FaultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("FaultCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
    public partial class CommunicationFaultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultDescriptionField;
        
        private string faultCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FaultDescription {
            get {
                return this.faultDescriptionField;
            }
            set {
                this.faultDescriptionField = value;
                this.RaisePropertyChanged("FaultDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FaultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("FaultCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
    public partial class ServerFaultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultDescriptionField;
        
        private string faultCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FaultDescription {
            get {
                return this.faultDescriptionField;
            }
            set {
                this.faultDescriptionField = value;
                this.RaisePropertyChanged("FaultDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FaultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("FaultCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.travco.co.uk/", ConfigurationName="HotelCancellationDetails.HotelCancellationDetailServicePortType")]
    public interface HotelCancellationDetailServicePortType {
        
        // CODEGEN: Generating message contract since the operation getHotelCancellationDetails is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getHotelCancellationDetails", ReplyAction="urn:getHotelCancellationDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.HotelCancellationDetails.ResponseDataFaultType), Action="urn:getHotelCancellationDetails", Name="ResponseDataFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.HotelCancellationDetails.ReceiveParserFaultType), Action="urn:getHotelCancellationDetails", Name="ReceiveParserFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.HotelCancellationDetails.SendParserFaultType), Action="urn:getHotelCancellationDetails", Name="SendParserFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.HotelCancellationDetails.UserFaultType), Action="urn:getHotelCancellationDetails", Name="UserFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.HotelCancellationDetails.CommunicationFaultType), Action="urn:getHotelCancellationDetails", Name="CommunicationFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.HotelCancellationDetails.ServerFaultType), Action="urn:getHotelCancellationDetails", Name="ServerFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgentBaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Detail[]))]
        TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsResponse getHotelCancellationDetails(TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getHotelCancellationDetails", ReplyAction="urn:getHotelCancellationDetailsResponse")]
        System.Threading.Tasks.Task<TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsResponse> getHotelCancellationDetailsAsync(TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsRequest request);
        
        // CODEGEN: Generating message contract since the operation getHotelCancellationDetailsNotCrossSeason is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getHotelCancellationDetailsNotCrossSeason", ReplyAction="urn:getHotelCancellationDetailsNotCrossSeasonResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.HotelCancellationDetails.ResponseDataFaultType), Action="urn:getHotelCancellationDetailsNotCrossSeason", Name="ResponseDataFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.HotelCancellationDetails.ReceiveParserFaultType), Action="urn:getHotelCancellationDetailsNotCrossSeason", Name="ReceiveParserFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.HotelCancellationDetails.SendParserFaultType), Action="urn:getHotelCancellationDetailsNotCrossSeason", Name="SendParserFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.HotelCancellationDetails.UserFaultType), Action="urn:getHotelCancellationDetailsNotCrossSeason", Name="UserFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.HotelCancellationDetails.CommunicationFaultType), Action="urn:getHotelCancellationDetailsNotCrossSeason", Name="CommunicationFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.FaultContractAttribute(typeof(TravillioXMLOutService.HotelCancellationDetails.ServerFaultType), Action="urn:getHotelCancellationDetailsNotCrossSeason", Name="ServerFault", Namespace="http://www.travco.co.uk/trlink/xsd/complextype")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgentBaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Detail[]))]
        TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsResponse getHotelCancellationDetailsNotCrossSeason(TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsNotCrossSeasonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getHotelCancellationDetailsNotCrossSeason", ReplyAction="urn:getHotelCancellationDetailsNotCrossSeasonResponse")]
        System.Threading.Tasks.Task<TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsResponse> getHotelCancellationDetailsNotCrossSeasonAsync(TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsNotCrossSeasonRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.travco.co.uk/trlink/xsd/hotelcancellationdetail/request")]
    public partial class getHotelCancellationDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestBaseType requestBaseField;
        
        private string hotelCodeField;
        
        private System.DateTime checkInDateField;
        
        private bool checkInDateFieldSpecified;
        
        private string durationField;
        
        private string cancellationChargeCodeField;
        
        private string cancellationChargeCodeForCrossSeasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestBaseType RequestBase {
            get {
                return this.requestBaseField;
            }
            set {
                this.requestBaseField = value;
                this.RaisePropertyChanged("RequestBase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HotelCode {
            get {
                return this.hotelCodeField;
            }
            set {
                this.hotelCodeField = value;
                this.RaisePropertyChanged("HotelCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime CheckInDate {
            get {
                return this.checkInDateField;
            }
            set {
                this.checkInDateField = value;
                this.RaisePropertyChanged("CheckInDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CheckInDateSpecified {
            get {
                return this.checkInDateFieldSpecified;
            }
            set {
                this.checkInDateFieldSpecified = value;
                this.RaisePropertyChanged("CheckInDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=3)]
        public string Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("Duration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CancellationChargeCode {
            get {
                return this.cancellationChargeCodeField;
            }
            set {
                this.cancellationChargeCodeField = value;
                this.RaisePropertyChanged("CancellationChargeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CancellationChargeCodeForCrossSeason {
            get {
                return this.cancellationChargeCodeForCrossSeasonField;
            }
            set {
                this.cancellationChargeCodeForCrossSeasonField = value;
                this.RaisePropertyChanged("CancellationChargeCodeForCrossSeason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.travco.co.uk/trlink/xsd/hotelcancellationdetail/response")]
    public partial class HotelCancellationDetailResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Response responseField;
        
        private string langTypeField;
        
        public HotelCancellationDetailResponse() {
            this.langTypeField = "en-GB";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Response Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("en-GB")]
        public string LangType {
            get {
                return this.langTypeField;
            }
            set {
                this.langTypeField = value;
                this.RaisePropertyChanged("LangType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.travco.co.uk/trlink/xsd/hotelcancellationdetail/response")]
    public partial class Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InfoType informationField;
        
        private Detail[] fullCancellationDetailsField;
        
        private CancellationCharge cancellationChargeField;
        
        private string hotelCodeField;
        
        private System.DateTime checkInDateField;
        
        private bool checkInDateFieldSpecified;
        
        private string durationField;
        
        private string cancellationChargeCodeField;
        
        private string cancellationChargeCodeForCrossSeasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public InfoType Information {
            get {
                return this.informationField;
            }
            set {
                this.informationField = value;
                this.RaisePropertyChanged("Information");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Detail", IsNullable=false)]
        public Detail[] FullCancellationDetails {
            get {
                return this.fullCancellationDetailsField;
            }
            set {
                this.fullCancellationDetailsField = value;
                this.RaisePropertyChanged("FullCancellationDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CancellationCharge CancellationCharge {
            get {
                return this.cancellationChargeField;
            }
            set {
                this.cancellationChargeField = value;
                this.RaisePropertyChanged("CancellationCharge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HotelCode {
            get {
                return this.hotelCodeField;
            }
            set {
                this.hotelCodeField = value;
                this.RaisePropertyChanged("HotelCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime CheckInDate {
            get {
                return this.checkInDateField;
            }
            set {
                this.checkInDateField = value;
                this.RaisePropertyChanged("CheckInDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CheckInDateSpecified {
            get {
                return this.checkInDateFieldSpecified;
            }
            set {
                this.checkInDateFieldSpecified = value;
                this.RaisePropertyChanged("CheckInDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("Duration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CancellationChargeCode {
            get {
                return this.cancellationChargeCodeField;
            }
            set {
                this.cancellationChargeCodeField = value;
                this.RaisePropertyChanged("CancellationChargeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CancellationChargeCodeForCrossSeason {
            get {
                return this.cancellationChargeCodeForCrossSeasonField;
            }
            set {
                this.cancellationChargeCodeForCrossSeasonField = value;
                this.RaisePropertyChanged("CancellationChargeCodeForCrossSeason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.travco.co.uk/trlink/xsd/hotelcancellationdetail/response")]
    public partial class CancellationCharge : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FirstCancellationCharge firstCancellationChargeField;
        
        private NextCancellationCharge[] nextCancellationChargesField;
        
        private string lastDateToCancelWithoutChargeField;
        
        private string beforeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FirstCancellationCharge FirstCancellationCharge {
            get {
                return this.firstCancellationChargeField;
            }
            set {
                this.firstCancellationChargeField = value;
                this.RaisePropertyChanged("FirstCancellationCharge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("NextCancellationCharge", IsNullable=false)]
        public NextCancellationCharge[] NextCancellationCharges {
            get {
                return this.nextCancellationChargesField;
            }
            set {
                this.nextCancellationChargesField = value;
                this.RaisePropertyChanged("NextCancellationCharges");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastDateToCancelWithoutCharge {
            get {
                return this.lastDateToCancelWithoutChargeField;
            }
            set {
                this.lastDateToCancelWithoutChargeField = value;
                this.RaisePropertyChanged("LastDateToCancelWithoutCharge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Before {
            get {
                return this.beforeField;
            }
            set {
                this.beforeField = value;
                this.RaisePropertyChanged("Before");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.travco.co.uk/trlink/xsd/hotelcancellationdetail/response")]
    public partial class FirstCancellationCharge : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fullCancellationNarrativeField;
        
        private string firstCancellationChargeDateField;
        
        private string afterField;
        
        private string noOfNtsField;
        
        private string atPercentageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FullCancellationNarrative {
            get {
                return this.fullCancellationNarrativeField;
            }
            set {
                this.fullCancellationNarrativeField = value;
                this.RaisePropertyChanged("FullCancellationNarrative");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FirstCancellationChargeDate {
            get {
                return this.firstCancellationChargeDateField;
            }
            set {
                this.firstCancellationChargeDateField = value;
                this.RaisePropertyChanged("FirstCancellationChargeDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string After {
            get {
                return this.afterField;
            }
            set {
                this.afterField = value;
                this.RaisePropertyChanged("After");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NoOfNts {
            get {
                return this.noOfNtsField;
            }
            set {
                this.noOfNtsField = value;
                this.RaisePropertyChanged("NoOfNts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AtPercentage {
            get {
                return this.atPercentageField;
            }
            set {
                this.atPercentageField = value;
                this.RaisePropertyChanged("AtPercentage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.travco.co.uk/trlink/xsd/hotelcancellationdetail/response")]
    public partial class NextCancellationCharge : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fullCancellationNarrativeField;
        
        private string nextCancellationChargeDateField;
        
        private string afterField;
        
        private string noOfNtsField;
        
        private string atPercentageField;
        
        private string plusNoOfNtsField;
        
        private string plusPercentageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FullCancellationNarrative {
            get {
                return this.fullCancellationNarrativeField;
            }
            set {
                this.fullCancellationNarrativeField = value;
                this.RaisePropertyChanged("FullCancellationNarrative");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NextCancellationChargeDate {
            get {
                return this.nextCancellationChargeDateField;
            }
            set {
                this.nextCancellationChargeDateField = value;
                this.RaisePropertyChanged("NextCancellationChargeDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string After {
            get {
                return this.afterField;
            }
            set {
                this.afterField = value;
                this.RaisePropertyChanged("After");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NoOfNts {
            get {
                return this.noOfNtsField;
            }
            set {
                this.noOfNtsField = value;
                this.RaisePropertyChanged("NoOfNts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AtPercentage {
            get {
                return this.atPercentageField;
            }
            set {
                this.atPercentageField = value;
                this.RaisePropertyChanged("AtPercentage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PlusNoOfNts {
            get {
                return this.plusNoOfNtsField;
            }
            set {
                this.plusNoOfNtsField = value;
                this.RaisePropertyChanged("PlusNoOfNts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PlusPercentage {
            get {
                return this.plusPercentageField;
            }
            set {
                this.plusPercentageField = value;
                this.RaisePropertyChanged("PlusPercentage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHotelCancellationDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/hotelcancellationdetail/request", Order=0)]
        public TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetails getHotelCancellationDetails;
        
        public getHotelCancellationDetailsRequest() {
        }
        
        public getHotelCancellationDetailsRequest(TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetails getHotelCancellationDetails) {
            this.getHotelCancellationDetails = getHotelCancellationDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHotelCancellationDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/hotelcancellationdetail/response", Order=0)]
        public TravillioXMLOutService.HotelCancellationDetails.HotelCancellationDetailResponse HotelCancellationDetailResponse;
        
        public getHotelCancellationDetailsResponse() {
        }
        
        public getHotelCancellationDetailsResponse(TravillioXMLOutService.HotelCancellationDetails.HotelCancellationDetailResponse HotelCancellationDetailResponse) {
            this.HotelCancellationDetailResponse = HotelCancellationDetailResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.travco.co.uk/trlink/xsd/hotelcancellationdetail/request")]
    public partial class getHotelCancellationDetailsNotCrossSeason : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestBaseType requestBaseField;
        
        private string hotelCodeField;
        
        private System.DateTime checkInDateField;
        
        private bool checkInDateFieldSpecified;
        
        private string durationField;
        
        private string cancellationChargeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestBaseType RequestBase {
            get {
                return this.requestBaseField;
            }
            set {
                this.requestBaseField = value;
                this.RaisePropertyChanged("RequestBase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HotelCode {
            get {
                return this.hotelCodeField;
            }
            set {
                this.hotelCodeField = value;
                this.RaisePropertyChanged("HotelCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime CheckInDate {
            get {
                return this.checkInDateField;
            }
            set {
                this.checkInDateField = value;
                this.RaisePropertyChanged("CheckInDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CheckInDateSpecified {
            get {
                return this.checkInDateFieldSpecified;
            }
            set {
                this.checkInDateFieldSpecified = value;
                this.RaisePropertyChanged("CheckInDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=3)]
        public string Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("Duration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CancellationChargeCode {
            get {
                return this.cancellationChargeCodeField;
            }
            set {
                this.cancellationChargeCodeField = value;
                this.RaisePropertyChanged("CancellationChargeCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHotelCancellationDetailsNotCrossSeasonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.travco.co.uk/trlink/xsd/hotelcancellationdetail/request", Order=0)]
        public TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsNotCrossSeason getHotelCancellationDetailsNotCrossSeason;
        
        public getHotelCancellationDetailsNotCrossSeasonRequest() {
        }
        
        public getHotelCancellationDetailsNotCrossSeasonRequest(TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsNotCrossSeason getHotelCancellationDetailsNotCrossSeason) {
            this.getHotelCancellationDetailsNotCrossSeason = getHotelCancellationDetailsNotCrossSeason;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HotelCancellationDetailServicePortTypeChannel : TravillioXMLOutService.HotelCancellationDetails.HotelCancellationDetailServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelCancellationDetailServicePortTypeClient : System.ServiceModel.ClientBase<TravillioXMLOutService.HotelCancellationDetails.HotelCancellationDetailServicePortType>, TravillioXMLOutService.HotelCancellationDetails.HotelCancellationDetailServicePortType {
        
        public HotelCancellationDetailServicePortTypeClient() {
        }
        
        public HotelCancellationDetailServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelCancellationDetailServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelCancellationDetailServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelCancellationDetailServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsResponse TravillioXMLOutService.HotelCancellationDetails.HotelCancellationDetailServicePortType.getHotelCancellationDetails(TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsRequest request) {
            return base.Channel.getHotelCancellationDetails(request);
        }
        
        public TravillioXMLOutService.HotelCancellationDetails.HotelCancellationDetailResponse getHotelCancellationDetails(TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetails getHotelCancellationDetails1) {
            TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsRequest inValue = new TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsRequest();
            inValue.getHotelCancellationDetails = getHotelCancellationDetails1;
            TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsResponse retVal = ((TravillioXMLOutService.HotelCancellationDetails.HotelCancellationDetailServicePortType)(this)).getHotelCancellationDetails(inValue);
            return retVal.HotelCancellationDetailResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsResponse> TravillioXMLOutService.HotelCancellationDetails.HotelCancellationDetailServicePortType.getHotelCancellationDetailsAsync(TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsRequest request) {
            return base.Channel.getHotelCancellationDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsResponse> getHotelCancellationDetailsAsync(TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetails getHotelCancellationDetails) {
            TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsRequest inValue = new TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsRequest();
            inValue.getHotelCancellationDetails = getHotelCancellationDetails;
            return ((TravillioXMLOutService.HotelCancellationDetails.HotelCancellationDetailServicePortType)(this)).getHotelCancellationDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsResponse TravillioXMLOutService.HotelCancellationDetails.HotelCancellationDetailServicePortType.getHotelCancellationDetailsNotCrossSeason(TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsNotCrossSeasonRequest request) {
            return base.Channel.getHotelCancellationDetailsNotCrossSeason(request);
        }
        
        public TravillioXMLOutService.HotelCancellationDetails.HotelCancellationDetailResponse getHotelCancellationDetailsNotCrossSeason(TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsNotCrossSeason getHotelCancellationDetailsNotCrossSeason1) {
            TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsNotCrossSeasonRequest inValue = new TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsNotCrossSeasonRequest();
            inValue.getHotelCancellationDetailsNotCrossSeason = getHotelCancellationDetailsNotCrossSeason1;
            TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsResponse retVal = ((TravillioXMLOutService.HotelCancellationDetails.HotelCancellationDetailServicePortType)(this)).getHotelCancellationDetailsNotCrossSeason(inValue);
            return retVal.HotelCancellationDetailResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsResponse> TravillioXMLOutService.HotelCancellationDetails.HotelCancellationDetailServicePortType.getHotelCancellationDetailsNotCrossSeasonAsync(TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsNotCrossSeasonRequest request) {
            return base.Channel.getHotelCancellationDetailsNotCrossSeasonAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsResponse> getHotelCancellationDetailsNotCrossSeasonAsync(TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsNotCrossSeason getHotelCancellationDetailsNotCrossSeason) {
            TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsNotCrossSeasonRequest inValue = new TravillioXMLOutService.HotelCancellationDetails.getHotelCancellationDetailsNotCrossSeasonRequest();
            inValue.getHotelCancellationDetailsNotCrossSeason = getHotelCancellationDetailsNotCrossSeason;
            return ((TravillioXMLOutService.HotelCancellationDetails.HotelCancellationDetailServicePortType)(this)).getHotelCancellationDetailsNotCrossSeasonAsync(inValue);
        }
    }
}
